service: talentmaker-api

useDotenv: false

provider:
  name: aws
  lambdaHashingVersion: "20201221"
  runtime: nodejs14.x
  stage: prod
  apiGateway:
    shouldStartNameWithService: true

functions:
  main:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
