name: CI

on:
  push: {}
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ci_password

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: pnpm

      - name: shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: test
          mysql version: "8.0.23"
          mysql root password: ci_password

      - name: Install deps
        run: pnpm install

      - name: ESLint
        run: pnpm lint

      - name: Audit
        run: pnpm audit -P

      - name: Generate prisma client
        run: pnpm prismaGenerate

      - name: Compile
        run: pnpm build -r

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password=ci_password --silent; do
            sleep 1
          done

      - name: Create env file
        run: echo "DB_URL="mysql://root:ci_password@localhost:3306/test"" > .env.testing

      - name: Run tests
        run: ERROR_LOG=1 pnpm test
